// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/doggy/orm/ent/predicate"
	"github.com/twiglab/doggy/orm/ent/upload"
	"github.com/twiglab/doggy/orm/ent/using"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUpload = "Upload"
	TypeUsing  = "Using"
)

// UploadMutation represents an operation that mutates the Upload nodes in the graph.
type UploadMutation struct {
	config
	op            Op
	typ           string
	id            *int
	create_time   *time.Time
	update_time   *time.Time
	sn            *string
	ip            *string
	last_time     *time.Time
	id_1          *string
	code_1        *string
	id_2          *string
	code_2        *string
	user          *string
	pwd           *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Upload, error)
	predicates    []predicate.Upload
}

var _ ent.Mutation = (*UploadMutation)(nil)

// uploadOption allows management of the mutation configuration using functional options.
type uploadOption func(*UploadMutation)

// newUploadMutation creates new mutation for the Upload entity.
func newUploadMutation(c config, op Op, opts ...uploadOption) *UploadMutation {
	m := &UploadMutation{
		config:        c,
		op:            op,
		typ:           TypeUpload,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUploadID sets the ID field of the mutation.
func withUploadID(id int) uploadOption {
	return func(m *UploadMutation) {
		var (
			err   error
			once  sync.Once
			value *Upload
		)
		m.oldValue = func(ctx context.Context) (*Upload, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Upload.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUpload sets the old Upload of the mutation.
func withUpload(node *Upload) uploadOption {
	return func(m *UploadMutation) {
		m.oldValue = func(context.Context) (*Upload, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UploadMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UploadMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UploadMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UploadMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Upload.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *UploadMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *UploadMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *UploadMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *UploadMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *UploadMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *UploadMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetSn sets the "sn" field.
func (m *UploadMutation) SetSn(s string) {
	m.sn = &s
}

// Sn returns the value of the "sn" field in the mutation.
func (m *UploadMutation) Sn() (r string, exists bool) {
	v := m.sn
	if v == nil {
		return
	}
	return *v, true
}

// OldSn returns the old "sn" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldSn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSn: %w", err)
	}
	return oldValue.Sn, nil
}

// ResetSn resets all changes to the "sn" field.
func (m *UploadMutation) ResetSn() {
	m.sn = nil
}

// SetIP sets the "ip" field.
func (m *UploadMutation) SetIP(s string) {
	m.ip = &s
}

// IP returns the value of the "ip" field in the mutation.
func (m *UploadMutation) IP() (r string, exists bool) {
	v := m.ip
	if v == nil {
		return
	}
	return *v, true
}

// OldIP returns the old "ip" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldIP(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIP: %w", err)
	}
	return oldValue.IP, nil
}

// ResetIP resets all changes to the "ip" field.
func (m *UploadMutation) ResetIP() {
	m.ip = nil
}

// SetLastTime sets the "last_time" field.
func (m *UploadMutation) SetLastTime(t time.Time) {
	m.last_time = &t
}

// LastTime returns the value of the "last_time" field in the mutation.
func (m *UploadMutation) LastTime() (r time.Time, exists bool) {
	v := m.last_time
	if v == nil {
		return
	}
	return *v, true
}

// OldLastTime returns the old "last_time" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldLastTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastTime: %w", err)
	}
	return oldValue.LastTime, nil
}

// ResetLastTime resets all changes to the "last_time" field.
func (m *UploadMutation) ResetLastTime() {
	m.last_time = nil
}

// SetID1 sets the "id_1" field.
func (m *UploadMutation) SetID1(s string) {
	m.id_1 = &s
}

// ID1 returns the value of the "id_1" field in the mutation.
func (m *UploadMutation) ID1() (r string, exists bool) {
	v := m.id_1
	if v == nil {
		return
	}
	return *v, true
}

// OldID1 returns the old "id_1" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldID1(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldID1 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldID1 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldID1: %w", err)
	}
	return oldValue.ID1, nil
}

// ClearID1 clears the value of the "id_1" field.
func (m *UploadMutation) ClearID1() {
	m.id_1 = nil
	m.clearedFields[upload.FieldID1] = struct{}{}
}

// ID1Cleared returns if the "id_1" field was cleared in this mutation.
func (m *UploadMutation) ID1Cleared() bool {
	_, ok := m.clearedFields[upload.FieldID1]
	return ok
}

// ResetID1 resets all changes to the "id_1" field.
func (m *UploadMutation) ResetID1() {
	m.id_1 = nil
	delete(m.clearedFields, upload.FieldID1)
}

// SetCode1 sets the "code_1" field.
func (m *UploadMutation) SetCode1(s string) {
	m.code_1 = &s
}

// Code1 returns the value of the "code_1" field in the mutation.
func (m *UploadMutation) Code1() (r string, exists bool) {
	v := m.code_1
	if v == nil {
		return
	}
	return *v, true
}

// OldCode1 returns the old "code_1" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldCode1(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCode1 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCode1 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCode1: %w", err)
	}
	return oldValue.Code1, nil
}

// ClearCode1 clears the value of the "code_1" field.
func (m *UploadMutation) ClearCode1() {
	m.code_1 = nil
	m.clearedFields[upload.FieldCode1] = struct{}{}
}

// Code1Cleared returns if the "code_1" field was cleared in this mutation.
func (m *UploadMutation) Code1Cleared() bool {
	_, ok := m.clearedFields[upload.FieldCode1]
	return ok
}

// ResetCode1 resets all changes to the "code_1" field.
func (m *UploadMutation) ResetCode1() {
	m.code_1 = nil
	delete(m.clearedFields, upload.FieldCode1)
}

// SetID2 sets the "id_2" field.
func (m *UploadMutation) SetID2(s string) {
	m.id_2 = &s
}

// ID2 returns the value of the "id_2" field in the mutation.
func (m *UploadMutation) ID2() (r string, exists bool) {
	v := m.id_2
	if v == nil {
		return
	}
	return *v, true
}

// OldID2 returns the old "id_2" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldID2(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldID2 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldID2 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldID2: %w", err)
	}
	return oldValue.ID2, nil
}

// ClearID2 clears the value of the "id_2" field.
func (m *UploadMutation) ClearID2() {
	m.id_2 = nil
	m.clearedFields[upload.FieldID2] = struct{}{}
}

// ID2Cleared returns if the "id_2" field was cleared in this mutation.
func (m *UploadMutation) ID2Cleared() bool {
	_, ok := m.clearedFields[upload.FieldID2]
	return ok
}

// ResetID2 resets all changes to the "id_2" field.
func (m *UploadMutation) ResetID2() {
	m.id_2 = nil
	delete(m.clearedFields, upload.FieldID2)
}

// SetCode2 sets the "code_2" field.
func (m *UploadMutation) SetCode2(s string) {
	m.code_2 = &s
}

// Code2 returns the value of the "code_2" field in the mutation.
func (m *UploadMutation) Code2() (r string, exists bool) {
	v := m.code_2
	if v == nil {
		return
	}
	return *v, true
}

// OldCode2 returns the old "code_2" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldCode2(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCode2 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCode2 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCode2: %w", err)
	}
	return oldValue.Code2, nil
}

// ClearCode2 clears the value of the "code_2" field.
func (m *UploadMutation) ClearCode2() {
	m.code_2 = nil
	m.clearedFields[upload.FieldCode2] = struct{}{}
}

// Code2Cleared returns if the "code_2" field was cleared in this mutation.
func (m *UploadMutation) Code2Cleared() bool {
	_, ok := m.clearedFields[upload.FieldCode2]
	return ok
}

// ResetCode2 resets all changes to the "code_2" field.
func (m *UploadMutation) ResetCode2() {
	m.code_2 = nil
	delete(m.clearedFields, upload.FieldCode2)
}

// SetUser sets the "user" field.
func (m *UploadMutation) SetUser(s string) {
	m.user = &s
}

// User returns the value of the "user" field in the mutation.
func (m *UploadMutation) User() (r string, exists bool) {
	v := m.user
	if v == nil {
		return
	}
	return *v, true
}

// OldUser returns the old "user" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldUser(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUser is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUser requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUser: %w", err)
	}
	return oldValue.User, nil
}

// ClearUser clears the value of the "user" field.
func (m *UploadMutation) ClearUser() {
	m.user = nil
	m.clearedFields[upload.FieldUser] = struct{}{}
}

// UserCleared returns if the "user" field was cleared in this mutation.
func (m *UploadMutation) UserCleared() bool {
	_, ok := m.clearedFields[upload.FieldUser]
	return ok
}

// ResetUser resets all changes to the "user" field.
func (m *UploadMutation) ResetUser() {
	m.user = nil
	delete(m.clearedFields, upload.FieldUser)
}

// SetPwd sets the "pwd" field.
func (m *UploadMutation) SetPwd(s string) {
	m.pwd = &s
}

// Pwd returns the value of the "pwd" field in the mutation.
func (m *UploadMutation) Pwd() (r string, exists bool) {
	v := m.pwd
	if v == nil {
		return
	}
	return *v, true
}

// OldPwd returns the old "pwd" field's value of the Upload entity.
// If the Upload object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UploadMutation) OldPwd(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPwd is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPwd requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPwd: %w", err)
	}
	return oldValue.Pwd, nil
}

// ClearPwd clears the value of the "pwd" field.
func (m *UploadMutation) ClearPwd() {
	m.pwd = nil
	m.clearedFields[upload.FieldPwd] = struct{}{}
}

// PwdCleared returns if the "pwd" field was cleared in this mutation.
func (m *UploadMutation) PwdCleared() bool {
	_, ok := m.clearedFields[upload.FieldPwd]
	return ok
}

// ResetPwd resets all changes to the "pwd" field.
func (m *UploadMutation) ResetPwd() {
	m.pwd = nil
	delete(m.clearedFields, upload.FieldPwd)
}

// Where appends a list predicates to the UploadMutation builder.
func (m *UploadMutation) Where(ps ...predicate.Upload) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UploadMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UploadMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Upload, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UploadMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UploadMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Upload).
func (m *UploadMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UploadMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.create_time != nil {
		fields = append(fields, upload.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, upload.FieldUpdateTime)
	}
	if m.sn != nil {
		fields = append(fields, upload.FieldSn)
	}
	if m.ip != nil {
		fields = append(fields, upload.FieldIP)
	}
	if m.last_time != nil {
		fields = append(fields, upload.FieldLastTime)
	}
	if m.id_1 != nil {
		fields = append(fields, upload.FieldID1)
	}
	if m.code_1 != nil {
		fields = append(fields, upload.FieldCode1)
	}
	if m.id_2 != nil {
		fields = append(fields, upload.FieldID2)
	}
	if m.code_2 != nil {
		fields = append(fields, upload.FieldCode2)
	}
	if m.user != nil {
		fields = append(fields, upload.FieldUser)
	}
	if m.pwd != nil {
		fields = append(fields, upload.FieldPwd)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UploadMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case upload.FieldCreateTime:
		return m.CreateTime()
	case upload.FieldUpdateTime:
		return m.UpdateTime()
	case upload.FieldSn:
		return m.Sn()
	case upload.FieldIP:
		return m.IP()
	case upload.FieldLastTime:
		return m.LastTime()
	case upload.FieldID1:
		return m.ID1()
	case upload.FieldCode1:
		return m.Code1()
	case upload.FieldID2:
		return m.ID2()
	case upload.FieldCode2:
		return m.Code2()
	case upload.FieldUser:
		return m.User()
	case upload.FieldPwd:
		return m.Pwd()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UploadMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case upload.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case upload.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case upload.FieldSn:
		return m.OldSn(ctx)
	case upload.FieldIP:
		return m.OldIP(ctx)
	case upload.FieldLastTime:
		return m.OldLastTime(ctx)
	case upload.FieldID1:
		return m.OldID1(ctx)
	case upload.FieldCode1:
		return m.OldCode1(ctx)
	case upload.FieldID2:
		return m.OldID2(ctx)
	case upload.FieldCode2:
		return m.OldCode2(ctx)
	case upload.FieldUser:
		return m.OldUser(ctx)
	case upload.FieldPwd:
		return m.OldPwd(ctx)
	}
	return nil, fmt.Errorf("unknown Upload field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UploadMutation) SetField(name string, value ent.Value) error {
	switch name {
	case upload.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case upload.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case upload.FieldSn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSn(v)
		return nil
	case upload.FieldIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIP(v)
		return nil
	case upload.FieldLastTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastTime(v)
		return nil
	case upload.FieldID1:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetID1(v)
		return nil
	case upload.FieldCode1:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCode1(v)
		return nil
	case upload.FieldID2:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetID2(v)
		return nil
	case upload.FieldCode2:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCode2(v)
		return nil
	case upload.FieldUser:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUser(v)
		return nil
	case upload.FieldPwd:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPwd(v)
		return nil
	}
	return fmt.Errorf("unknown Upload field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UploadMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UploadMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UploadMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Upload numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UploadMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(upload.FieldID1) {
		fields = append(fields, upload.FieldID1)
	}
	if m.FieldCleared(upload.FieldCode1) {
		fields = append(fields, upload.FieldCode1)
	}
	if m.FieldCleared(upload.FieldID2) {
		fields = append(fields, upload.FieldID2)
	}
	if m.FieldCleared(upload.FieldCode2) {
		fields = append(fields, upload.FieldCode2)
	}
	if m.FieldCleared(upload.FieldUser) {
		fields = append(fields, upload.FieldUser)
	}
	if m.FieldCleared(upload.FieldPwd) {
		fields = append(fields, upload.FieldPwd)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UploadMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UploadMutation) ClearField(name string) error {
	switch name {
	case upload.FieldID1:
		m.ClearID1()
		return nil
	case upload.FieldCode1:
		m.ClearCode1()
		return nil
	case upload.FieldID2:
		m.ClearID2()
		return nil
	case upload.FieldCode2:
		m.ClearCode2()
		return nil
	case upload.FieldUser:
		m.ClearUser()
		return nil
	case upload.FieldPwd:
		m.ClearPwd()
		return nil
	}
	return fmt.Errorf("unknown Upload nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UploadMutation) ResetField(name string) error {
	switch name {
	case upload.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case upload.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case upload.FieldSn:
		m.ResetSn()
		return nil
	case upload.FieldIP:
		m.ResetIP()
		return nil
	case upload.FieldLastTime:
		m.ResetLastTime()
		return nil
	case upload.FieldID1:
		m.ResetID1()
		return nil
	case upload.FieldCode1:
		m.ResetCode1()
		return nil
	case upload.FieldID2:
		m.ResetID2()
		return nil
	case upload.FieldCode2:
		m.ResetCode2()
		return nil
	case upload.FieldUser:
		m.ResetUser()
		return nil
	case upload.FieldPwd:
		m.ResetPwd()
		return nil
	}
	return fmt.Errorf("unknown Upload field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UploadMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UploadMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UploadMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UploadMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UploadMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UploadMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UploadMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Upload unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UploadMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Upload edge %s", name)
}

// UsingMutation represents an operation that mutates the Using nodes in the graph.
type UsingMutation struct {
	config
	op            Op
	typ           string
	id            *int
	create_time   *time.Time
	update_time   *time.Time
	sn            *string
	uuid          *string
	device_id     *string
	alg           *string
	name          *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Using, error)
	predicates    []predicate.Using
}

var _ ent.Mutation = (*UsingMutation)(nil)

// usingOption allows management of the mutation configuration using functional options.
type usingOption func(*UsingMutation)

// newUsingMutation creates new mutation for the Using entity.
func newUsingMutation(c config, op Op, opts ...usingOption) *UsingMutation {
	m := &UsingMutation{
		config:        c,
		op:            op,
		typ:           TypeUsing,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUsingID sets the ID field of the mutation.
func withUsingID(id int) usingOption {
	return func(m *UsingMutation) {
		var (
			err   error
			once  sync.Once
			value *Using
		)
		m.oldValue = func(ctx context.Context) (*Using, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Using.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUsing sets the old Using of the mutation.
func withUsing(node *Using) usingOption {
	return func(m *UsingMutation) {
		m.oldValue = func(context.Context) (*Using, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UsingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UsingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UsingMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UsingMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Using.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *UsingMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *UsingMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Using entity.
// If the Using object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UsingMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *UsingMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *UsingMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *UsingMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Using entity.
// If the Using object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UsingMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *UsingMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetSn sets the "sn" field.
func (m *UsingMutation) SetSn(s string) {
	m.sn = &s
}

// Sn returns the value of the "sn" field in the mutation.
func (m *UsingMutation) Sn() (r string, exists bool) {
	v := m.sn
	if v == nil {
		return
	}
	return *v, true
}

// OldSn returns the old "sn" field's value of the Using entity.
// If the Using object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UsingMutation) OldSn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSn: %w", err)
	}
	return oldValue.Sn, nil
}

// ResetSn resets all changes to the "sn" field.
func (m *UsingMutation) ResetSn() {
	m.sn = nil
}

// SetUUID sets the "uuid" field.
func (m *UsingMutation) SetUUID(s string) {
	m.uuid = &s
}

// UUID returns the value of the "uuid" field in the mutation.
func (m *UsingMutation) UUID() (r string, exists bool) {
	v := m.uuid
	if v == nil {
		return
	}
	return *v, true
}

// OldUUID returns the old "uuid" field's value of the Using entity.
// If the Using object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UsingMutation) OldUUID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUUID: %w", err)
	}
	return oldValue.UUID, nil
}

// ResetUUID resets all changes to the "uuid" field.
func (m *UsingMutation) ResetUUID() {
	m.uuid = nil
}

// SetDeviceID sets the "device_id" field.
func (m *UsingMutation) SetDeviceID(s string) {
	m.device_id = &s
}

// DeviceID returns the value of the "device_id" field in the mutation.
func (m *UsingMutation) DeviceID() (r string, exists bool) {
	v := m.device_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDeviceID returns the old "device_id" field's value of the Using entity.
// If the Using object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UsingMutation) OldDeviceID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeviceID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeviceID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeviceID: %w", err)
	}
	return oldValue.DeviceID, nil
}

// ResetDeviceID resets all changes to the "device_id" field.
func (m *UsingMutation) ResetDeviceID() {
	m.device_id = nil
}

// SetAlg sets the "alg" field.
func (m *UsingMutation) SetAlg(s string) {
	m.alg = &s
}

// Alg returns the value of the "alg" field in the mutation.
func (m *UsingMutation) Alg() (r string, exists bool) {
	v := m.alg
	if v == nil {
		return
	}
	return *v, true
}

// OldAlg returns the old "alg" field's value of the Using entity.
// If the Using object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UsingMutation) OldAlg(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAlg is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAlg requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAlg: %w", err)
	}
	return oldValue.Alg, nil
}

// ResetAlg resets all changes to the "alg" field.
func (m *UsingMutation) ResetAlg() {
	m.alg = nil
}

// SetName sets the "name" field.
func (m *UsingMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UsingMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Using entity.
// If the Using object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UsingMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *UsingMutation) ClearName() {
	m.name = nil
	m.clearedFields[using.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *UsingMutation) NameCleared() bool {
	_, ok := m.clearedFields[using.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *UsingMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, using.FieldName)
}

// Where appends a list predicates to the UsingMutation builder.
func (m *UsingMutation) Where(ps ...predicate.Using) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UsingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UsingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Using, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UsingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UsingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Using).
func (m *UsingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UsingMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.create_time != nil {
		fields = append(fields, using.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, using.FieldUpdateTime)
	}
	if m.sn != nil {
		fields = append(fields, using.FieldSn)
	}
	if m.uuid != nil {
		fields = append(fields, using.FieldUUID)
	}
	if m.device_id != nil {
		fields = append(fields, using.FieldDeviceID)
	}
	if m.alg != nil {
		fields = append(fields, using.FieldAlg)
	}
	if m.name != nil {
		fields = append(fields, using.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UsingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case using.FieldCreateTime:
		return m.CreateTime()
	case using.FieldUpdateTime:
		return m.UpdateTime()
	case using.FieldSn:
		return m.Sn()
	case using.FieldUUID:
		return m.UUID()
	case using.FieldDeviceID:
		return m.DeviceID()
	case using.FieldAlg:
		return m.Alg()
	case using.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UsingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case using.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case using.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case using.FieldSn:
		return m.OldSn(ctx)
	case using.FieldUUID:
		return m.OldUUID(ctx)
	case using.FieldDeviceID:
		return m.OldDeviceID(ctx)
	case using.FieldAlg:
		return m.OldAlg(ctx)
	case using.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Using field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UsingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case using.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case using.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case using.FieldSn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSn(v)
		return nil
	case using.FieldUUID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUUID(v)
		return nil
	case using.FieldDeviceID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeviceID(v)
		return nil
	case using.FieldAlg:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAlg(v)
		return nil
	case using.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Using field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UsingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UsingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UsingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Using numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UsingMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(using.FieldName) {
		fields = append(fields, using.FieldName)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UsingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UsingMutation) ClearField(name string) error {
	switch name {
	case using.FieldName:
		m.ClearName()
		return nil
	}
	return fmt.Errorf("unknown Using nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UsingMutation) ResetField(name string) error {
	switch name {
	case using.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case using.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case using.FieldSn:
		m.ResetSn()
		return nil
	case using.FieldUUID:
		m.ResetUUID()
		return nil
	case using.FieldDeviceID:
		m.ResetDeviceID()
		return nil
	case using.FieldAlg:
		m.ResetAlg()
		return nil
	case using.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Using field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UsingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UsingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UsingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UsingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UsingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UsingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UsingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Using unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UsingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Using edge %s", name)
}
