// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/doggy/orm/ent/pos"
	"github.com/twiglab/doggy/orm/ent/predicate"
)

// PosUpdate is the builder for updating Pos entities.
type PosUpdate struct {
	config
	hooks    []Hook
	mutation *PosMutation
}

// Where appends a list predicates to the PosUpdate builder.
func (pu *PosUpdate) Where(ps ...predicate.Pos) *PosUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdateTime sets the "update_time" field.
func (pu *PosUpdate) SetUpdateTime(t time.Time) *PosUpdate {
	pu.mutation.SetUpdateTime(t)
	return pu
}

// SetFloor sets the "floor" field.
func (pu *PosUpdate) SetFloor(s string) *PosUpdate {
	pu.mutation.SetFloor(s)
	return pu
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (pu *PosUpdate) SetNillableFloor(s *string) *PosUpdate {
	if s != nil {
		pu.SetFloor(*s)
	}
	return pu
}

// ClearFloor clears the value of the "floor" field.
func (pu *PosUpdate) ClearFloor() *PosUpdate {
	pu.mutation.ClearFloor()
	return pu
}

// SetBuilding sets the "building" field.
func (pu *PosUpdate) SetBuilding(s string) *PosUpdate {
	pu.mutation.SetBuilding(s)
	return pu
}

// SetNillableBuilding sets the "building" field if the given value is not nil.
func (pu *PosUpdate) SetNillableBuilding(s *string) *PosUpdate {
	if s != nil {
		pu.SetBuilding(*s)
	}
	return pu
}

// ClearBuilding clears the value of the "building" field.
func (pu *PosUpdate) ClearBuilding() *PosUpdate {
	pu.mutation.ClearBuilding()
	return pu
}

// SetArea sets the "area" field.
func (pu *PosUpdate) SetArea(s string) *PosUpdate {
	pu.mutation.SetArea(s)
	return pu
}

// SetNillableArea sets the "area" field if the given value is not nil.
func (pu *PosUpdate) SetNillableArea(s *string) *PosUpdate {
	if s != nil {
		pu.SetArea(*s)
	}
	return pu
}

// ClearArea clears the value of the "area" field.
func (pu *PosUpdate) ClearArea() *PosUpdate {
	pu.mutation.ClearArea()
	return pu
}

// Mutation returns the PosMutation object of the builder.
func (pu *PosUpdate) Mutation() *PosMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PosUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PosUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PosUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PosUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PosUpdate) defaults() {
	if _, ok := pu.mutation.UpdateTime(); !ok {
		v := pos.UpdateDefaultUpdateTime()
		pu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PosUpdate) check() error {
	if v, ok := pu.mutation.Floor(); ok {
		if err := pos.FloorValidator(v); err != nil {
			return &ValidationError{Name: "floor", err: fmt.Errorf(`ent: validator failed for field "Pos.floor": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Building(); ok {
		if err := pos.BuildingValidator(v); err != nil {
			return &ValidationError{Name: "building", err: fmt.Errorf(`ent: validator failed for field "Pos.building": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Area(); ok {
		if err := pos.AreaValidator(v); err != nil {
			return &ValidationError{Name: "area", err: fmt.Errorf(`ent: validator failed for field "Pos.area": %w`, err)}
		}
	}
	return nil
}

func (pu *PosUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(pos.Table, pos.Columns, sqlgraph.NewFieldSpec(pos.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdateTime(); ok {
		_spec.SetField(pos.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Floor(); ok {
		_spec.SetField(pos.FieldFloor, field.TypeString, value)
	}
	if pu.mutation.FloorCleared() {
		_spec.ClearField(pos.FieldFloor, field.TypeString)
	}
	if value, ok := pu.mutation.Building(); ok {
		_spec.SetField(pos.FieldBuilding, field.TypeString, value)
	}
	if pu.mutation.BuildingCleared() {
		_spec.ClearField(pos.FieldBuilding, field.TypeString)
	}
	if value, ok := pu.mutation.Area(); ok {
		_spec.SetField(pos.FieldArea, field.TypeString, value)
	}
	if pu.mutation.AreaCleared() {
		_spec.ClearField(pos.FieldArea, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pos.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PosUpdateOne is the builder for updating a single Pos entity.
type PosUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PosMutation
}

// SetUpdateTime sets the "update_time" field.
func (puo *PosUpdateOne) SetUpdateTime(t time.Time) *PosUpdateOne {
	puo.mutation.SetUpdateTime(t)
	return puo
}

// SetFloor sets the "floor" field.
func (puo *PosUpdateOne) SetFloor(s string) *PosUpdateOne {
	puo.mutation.SetFloor(s)
	return puo
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (puo *PosUpdateOne) SetNillableFloor(s *string) *PosUpdateOne {
	if s != nil {
		puo.SetFloor(*s)
	}
	return puo
}

// ClearFloor clears the value of the "floor" field.
func (puo *PosUpdateOne) ClearFloor() *PosUpdateOne {
	puo.mutation.ClearFloor()
	return puo
}

// SetBuilding sets the "building" field.
func (puo *PosUpdateOne) SetBuilding(s string) *PosUpdateOne {
	puo.mutation.SetBuilding(s)
	return puo
}

// SetNillableBuilding sets the "building" field if the given value is not nil.
func (puo *PosUpdateOne) SetNillableBuilding(s *string) *PosUpdateOne {
	if s != nil {
		puo.SetBuilding(*s)
	}
	return puo
}

// ClearBuilding clears the value of the "building" field.
func (puo *PosUpdateOne) ClearBuilding() *PosUpdateOne {
	puo.mutation.ClearBuilding()
	return puo
}

// SetArea sets the "area" field.
func (puo *PosUpdateOne) SetArea(s string) *PosUpdateOne {
	puo.mutation.SetArea(s)
	return puo
}

// SetNillableArea sets the "area" field if the given value is not nil.
func (puo *PosUpdateOne) SetNillableArea(s *string) *PosUpdateOne {
	if s != nil {
		puo.SetArea(*s)
	}
	return puo
}

// ClearArea clears the value of the "area" field.
func (puo *PosUpdateOne) ClearArea() *PosUpdateOne {
	puo.mutation.ClearArea()
	return puo
}

// Mutation returns the PosMutation object of the builder.
func (puo *PosUpdateOne) Mutation() *PosMutation {
	return puo.mutation
}

// Where appends a list predicates to the PosUpdate builder.
func (puo *PosUpdateOne) Where(ps ...predicate.Pos) *PosUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PosUpdateOne) Select(field string, fields ...string) *PosUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Pos entity.
func (puo *PosUpdateOne) Save(ctx context.Context) (*Pos, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PosUpdateOne) SaveX(ctx context.Context) *Pos {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PosUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PosUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PosUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdateTime(); !ok {
		v := pos.UpdateDefaultUpdateTime()
		puo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PosUpdateOne) check() error {
	if v, ok := puo.mutation.Floor(); ok {
		if err := pos.FloorValidator(v); err != nil {
			return &ValidationError{Name: "floor", err: fmt.Errorf(`ent: validator failed for field "Pos.floor": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Building(); ok {
		if err := pos.BuildingValidator(v); err != nil {
			return &ValidationError{Name: "building", err: fmt.Errorf(`ent: validator failed for field "Pos.building": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Area(); ok {
		if err := pos.AreaValidator(v); err != nil {
			return &ValidationError{Name: "area", err: fmt.Errorf(`ent: validator failed for field "Pos.area": %w`, err)}
		}
	}
	return nil
}

func (puo *PosUpdateOne) sqlSave(ctx context.Context) (_node *Pos, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pos.Table, pos.Columns, sqlgraph.NewFieldSpec(pos.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pos.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pos.FieldID)
		for _, f := range fields {
			if !pos.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pos.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdateTime(); ok {
		_spec.SetField(pos.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Floor(); ok {
		_spec.SetField(pos.FieldFloor, field.TypeString, value)
	}
	if puo.mutation.FloorCleared() {
		_spec.ClearField(pos.FieldFloor, field.TypeString)
	}
	if value, ok := puo.mutation.Building(); ok {
		_spec.SetField(pos.FieldBuilding, field.TypeString, value)
	}
	if puo.mutation.BuildingCleared() {
		_spec.ClearField(pos.FieldBuilding, field.TypeString)
	}
	if value, ok := puo.mutation.Area(); ok {
		_spec.SetField(pos.FieldArea, field.TypeString, value)
	}
	if puo.mutation.AreaCleared() {
		_spec.ClearField(pos.FieldArea, field.TypeString)
	}
	_node = &Pos{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pos.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
