// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/twiglab/doggy/orm/ent/point"
	"github.com/twiglab/doggy/orm/ent/upload"
	"github.com/twiglab/doggy/orm/ent/using"
	"github.com/twiglab/doggy/orm/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pointMixin := schema.Point{}.Mixin()
	pointMixinFields0 := pointMixin[0].Fields()
	_ = pointMixinFields0
	pointFields := schema.Point{}.Fields()
	_ = pointFields
	// pointDescCreateTime is the schema descriptor for create_time field.
	pointDescCreateTime := pointMixinFields0[0].Descriptor()
	// point.DefaultCreateTime holds the default value on creation for the create_time field.
	point.DefaultCreateTime = pointDescCreateTime.Default.(func() time.Time)
	// pointDescUpdateTime is the schema descriptor for update_time field.
	pointDescUpdateTime := pointMixinFields0[1].Descriptor()
	// point.DefaultUpdateTime holds the default value on creation for the update_time field.
	point.DefaultUpdateTime = pointDescUpdateTime.Default.(func() time.Time)
	// point.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	point.UpdateDefaultUpdateTime = pointDescUpdateTime.UpdateDefault.(func() time.Time)
	// pointDescSn is the schema descriptor for sn field.
	pointDescSn := pointFields[0].Descriptor()
	// point.SnValidator is a validator for the "sn" field. It is called by the builders before save.
	point.SnValidator = func() func(string) error {
		validators := pointDescSn.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(sn string) error {
			for _, fn := range fns {
				if err := fn(sn); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pointDescPos is the schema descriptor for pos field.
	pointDescPos := pointFields[1].Descriptor()
	// point.PosValidator is a validator for the "pos" field. It is called by the builders before save.
	point.PosValidator = func() func(string) error {
		validators := pointDescPos.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(pos string) error {
			for _, fn := range fns {
				if err := fn(pos); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pointDescFloor is the schema descriptor for floor field.
	pointDescFloor := pointFields[2].Descriptor()
	// point.FloorValidator is a validator for the "floor" field. It is called by the builders before save.
	point.FloorValidator = pointDescFloor.Validators[0].(func(string) error)
	// pointDescBuilding is the schema descriptor for building field.
	pointDescBuilding := pointFields[3].Descriptor()
	// point.BuildingValidator is a validator for the "building" field. It is called by the builders before save.
	point.BuildingValidator = pointDescBuilding.Validators[0].(func(string) error)
	// pointDescArea is the schema descriptor for area field.
	pointDescArea := pointFields[4].Descriptor()
	// point.AreaValidator is a validator for the "area" field. It is called by the builders before save.
	point.AreaValidator = pointDescArea.Validators[0].(func(string) error)
	uploadMixin := schema.Upload{}.Mixin()
	uploadMixinFields0 := uploadMixin[0].Fields()
	_ = uploadMixinFields0
	uploadFields := schema.Upload{}.Fields()
	_ = uploadFields
	// uploadDescCreateTime is the schema descriptor for create_time field.
	uploadDescCreateTime := uploadMixinFields0[0].Descriptor()
	// upload.DefaultCreateTime holds the default value on creation for the create_time field.
	upload.DefaultCreateTime = uploadDescCreateTime.Default.(func() time.Time)
	// uploadDescUpdateTime is the schema descriptor for update_time field.
	uploadDescUpdateTime := uploadMixinFields0[1].Descriptor()
	// upload.DefaultUpdateTime holds the default value on creation for the update_time field.
	upload.DefaultUpdateTime = uploadDescUpdateTime.Default.(func() time.Time)
	// upload.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	upload.UpdateDefaultUpdateTime = uploadDescUpdateTime.UpdateDefault.(func() time.Time)
	// uploadDescSn is the schema descriptor for sn field.
	uploadDescSn := uploadFields[0].Descriptor()
	// upload.SnValidator is a validator for the "sn" field. It is called by the builders before save.
	upload.SnValidator = func() func(string) error {
		validators := uploadDescSn.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(sn string) error {
			for _, fn := range fns {
				if err := fn(sn); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadDescIP is the schema descriptor for ip field.
	uploadDescIP := uploadFields[1].Descriptor()
	// upload.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	upload.IPValidator = func() func(string) error {
		validators := uploadDescIP.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ip string) error {
			for _, fn := range fns {
				if err := fn(ip); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadDescLastTime is the schema descriptor for last_time field.
	uploadDescLastTime := uploadFields[2].Descriptor()
	// upload.DefaultLastTime holds the default value on creation for the last_time field.
	upload.DefaultLastTime = uploadDescLastTime.Default.(func() time.Time)
	// upload.UpdateDefaultLastTime holds the default value on update for the last_time field.
	upload.UpdateDefaultLastTime = uploadDescLastTime.UpdateDefault.(func() time.Time)
	// uploadDescID1 is the schema descriptor for id_1 field.
	uploadDescID1 := uploadFields[3].Descriptor()
	// upload.ID1Validator is a validator for the "id_1" field. It is called by the builders before save.
	upload.ID1Validator = uploadDescID1.Validators[0].(func(string) error)
	// uploadDescID2 is the schema descriptor for id_2 field.
	uploadDescID2 := uploadFields[4].Descriptor()
	// upload.ID2Validator is a validator for the "id_2" field. It is called by the builders before save.
	upload.ID2Validator = uploadDescID2.Validators[0].(func(string) error)
	usingMixin := schema.Using{}.Mixin()
	usingMixinFields0 := usingMixin[0].Fields()
	_ = usingMixinFields0
	usingFields := schema.Using{}.Fields()
	_ = usingFields
	// usingDescCreateTime is the schema descriptor for create_time field.
	usingDescCreateTime := usingMixinFields0[0].Descriptor()
	// using.DefaultCreateTime holds the default value on creation for the create_time field.
	using.DefaultCreateTime = usingDescCreateTime.Default.(func() time.Time)
	// usingDescUpdateTime is the schema descriptor for update_time field.
	usingDescUpdateTime := usingMixinFields0[1].Descriptor()
	// using.DefaultUpdateTime holds the default value on creation for the update_time field.
	using.DefaultUpdateTime = usingDescUpdateTime.Default.(func() time.Time)
	// using.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	using.UpdateDefaultUpdateTime = usingDescUpdateTime.UpdateDefault.(func() time.Time)
	// usingDescSn is the schema descriptor for sn field.
	usingDescSn := usingFields[0].Descriptor()
	// using.SnValidator is a validator for the "sn" field. It is called by the builders before save.
	using.SnValidator = func() func(string) error {
		validators := usingDescSn.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(sn string) error {
			for _, fn := range fns {
				if err := fn(sn); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usingDescUUID is the schema descriptor for uuid field.
	usingDescUUID := usingFields[1].Descriptor()
	// using.UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	using.UUIDValidator = func() func(string) error {
		validators := usingDescUUID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(uuid string) error {
			for _, fn := range fns {
				if err := fn(uuid); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usingDescAlg is the schema descriptor for alg field.
	usingDescAlg := usingFields[2].Descriptor()
	// using.AlgValidator is a validator for the "alg" field. It is called by the builders before save.
	using.AlgValidator = func() func(string) error {
		validators := usingDescAlg.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(alg string) error {
			for _, fn := range fns {
				if err := fn(alg); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usingDescName is the schema descriptor for name field.
	usingDescName := usingFields[3].Descriptor()
	// using.NameValidator is a validator for the "name" field. It is called by the builders before save.
	using.NameValidator = usingDescName.Validators[0].(func(string) error)
}
