// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/doggy/orm/ent/predicate"
	"github.com/twiglab/doggy/orm/ent/setup"
)

// SetupUpdate is the builder for updating Setup entities.
type SetupUpdate struct {
	config
	hooks    []Hook
	mutation *SetupMutation
}

// Where appends a list predicates to the SetupUpdate builder.
func (su *SetupUpdate) Where(ps ...predicate.Setup) *SetupUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdateTime sets the "update_time" field.
func (su *SetupUpdate) SetUpdateTime(t time.Time) *SetupUpdate {
	su.mutation.SetUpdateTime(t)
	return su
}

// SetIP sets the "ip" field.
func (su *SetupUpdate) SetIP(s string) *SetupUpdate {
	su.mutation.SetIP(s)
	return su
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (su *SetupUpdate) SetNillableIP(s *string) *SetupUpdate {
	if s != nil {
		su.SetIP(*s)
	}
	return su
}

// SetLastTime sets the "last_time" field.
func (su *SetupUpdate) SetLastTime(t time.Time) *SetupUpdate {
	su.mutation.SetLastTime(t)
	return su
}

// SetUser sets the "user" field.
func (su *SetupUpdate) SetUser(s string) *SetupUpdate {
	su.mutation.SetUser(s)
	return su
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (su *SetupUpdate) SetNillableUser(s *string) *SetupUpdate {
	if s != nil {
		su.SetUser(*s)
	}
	return su
}

// ClearUser clears the value of the "user" field.
func (su *SetupUpdate) ClearUser() *SetupUpdate {
	su.mutation.ClearUser()
	return su
}

// SetPwd sets the "pwd" field.
func (su *SetupUpdate) SetPwd(s string) *SetupUpdate {
	su.mutation.SetPwd(s)
	return su
}

// SetNillablePwd sets the "pwd" field if the given value is not nil.
func (su *SetupUpdate) SetNillablePwd(s *string) *SetupUpdate {
	if s != nil {
		su.SetPwd(*s)
	}
	return su
}

// ClearPwd clears the value of the "pwd" field.
func (su *SetupUpdate) ClearPwd() *SetupUpdate {
	su.mutation.ClearPwd()
	return su
}

// SetUuid1 sets the "uuid1" field.
func (su *SetupUpdate) SetUuid1(s string) *SetupUpdate {
	su.mutation.SetUuid1(s)
	return su
}

// SetNillableUuid1 sets the "uuid1" field if the given value is not nil.
func (su *SetupUpdate) SetNillableUuid1(s *string) *SetupUpdate {
	if s != nil {
		su.SetUuid1(*s)
	}
	return su
}

// SetUuid2 sets the "uuid2" field.
func (su *SetupUpdate) SetUuid2(s string) *SetupUpdate {
	su.mutation.SetUuid2(s)
	return su
}

// SetNillableUuid2 sets the "uuid2" field if the given value is not nil.
func (su *SetupUpdate) SetNillableUuid2(s *string) *SetupUpdate {
	if s != nil {
		su.SetUuid2(*s)
	}
	return su
}

// Mutation returns the SetupMutation object of the builder.
func (su *SetupUpdate) Mutation() *SetupMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SetupUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SetupUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SetupUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SetupUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SetupUpdate) defaults() {
	if _, ok := su.mutation.UpdateTime(); !ok {
		v := setup.UpdateDefaultUpdateTime()
		su.mutation.SetUpdateTime(v)
	}
	if _, ok := su.mutation.LastTime(); !ok {
		v := setup.UpdateDefaultLastTime()
		su.mutation.SetLastTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SetupUpdate) check() error {
	if v, ok := su.mutation.IP(); ok {
		if err := setup.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Setup.ip": %w`, err)}
		}
	}
	if v, ok := su.mutation.User(); ok {
		if err := setup.UserValidator(v); err != nil {
			return &ValidationError{Name: "user", err: fmt.Errorf(`ent: validator failed for field "Setup.user": %w`, err)}
		}
	}
	if v, ok := su.mutation.Pwd(); ok {
		if err := setup.PwdValidator(v); err != nil {
			return &ValidationError{Name: "pwd", err: fmt.Errorf(`ent: validator failed for field "Setup.pwd": %w`, err)}
		}
	}
	if v, ok := su.mutation.Uuid1(); ok {
		if err := setup.Uuid1Validator(v); err != nil {
			return &ValidationError{Name: "uuid1", err: fmt.Errorf(`ent: validator failed for field "Setup.uuid1": %w`, err)}
		}
	}
	if v, ok := su.mutation.Uuid2(); ok {
		if err := setup.Uuid2Validator(v); err != nil {
			return &ValidationError{Name: "uuid2", err: fmt.Errorf(`ent: validator failed for field "Setup.uuid2": %w`, err)}
		}
	}
	return nil
}

func (su *SetupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(setup.Table, setup.Columns, sqlgraph.NewFieldSpec(setup.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdateTime(); ok {
		_spec.SetField(setup.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.IP(); ok {
		_spec.SetField(setup.FieldIP, field.TypeString, value)
	}
	if value, ok := su.mutation.LastTime(); ok {
		_spec.SetField(setup.FieldLastTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.User(); ok {
		_spec.SetField(setup.FieldUser, field.TypeString, value)
	}
	if su.mutation.UserCleared() {
		_spec.ClearField(setup.FieldUser, field.TypeString)
	}
	if value, ok := su.mutation.Pwd(); ok {
		_spec.SetField(setup.FieldPwd, field.TypeString, value)
	}
	if su.mutation.PwdCleared() {
		_spec.ClearField(setup.FieldPwd, field.TypeString)
	}
	if value, ok := su.mutation.Uuid1(); ok {
		_spec.SetField(setup.FieldUuid1, field.TypeString, value)
	}
	if value, ok := su.mutation.Uuid2(); ok {
		_spec.SetField(setup.FieldUuid2, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{setup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SetupUpdateOne is the builder for updating a single Setup entity.
type SetupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SetupMutation
}

// SetUpdateTime sets the "update_time" field.
func (suo *SetupUpdateOne) SetUpdateTime(t time.Time) *SetupUpdateOne {
	suo.mutation.SetUpdateTime(t)
	return suo
}

// SetIP sets the "ip" field.
func (suo *SetupUpdateOne) SetIP(s string) *SetupUpdateOne {
	suo.mutation.SetIP(s)
	return suo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (suo *SetupUpdateOne) SetNillableIP(s *string) *SetupUpdateOne {
	if s != nil {
		suo.SetIP(*s)
	}
	return suo
}

// SetLastTime sets the "last_time" field.
func (suo *SetupUpdateOne) SetLastTime(t time.Time) *SetupUpdateOne {
	suo.mutation.SetLastTime(t)
	return suo
}

// SetUser sets the "user" field.
func (suo *SetupUpdateOne) SetUser(s string) *SetupUpdateOne {
	suo.mutation.SetUser(s)
	return suo
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (suo *SetupUpdateOne) SetNillableUser(s *string) *SetupUpdateOne {
	if s != nil {
		suo.SetUser(*s)
	}
	return suo
}

// ClearUser clears the value of the "user" field.
func (suo *SetupUpdateOne) ClearUser() *SetupUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// SetPwd sets the "pwd" field.
func (suo *SetupUpdateOne) SetPwd(s string) *SetupUpdateOne {
	suo.mutation.SetPwd(s)
	return suo
}

// SetNillablePwd sets the "pwd" field if the given value is not nil.
func (suo *SetupUpdateOne) SetNillablePwd(s *string) *SetupUpdateOne {
	if s != nil {
		suo.SetPwd(*s)
	}
	return suo
}

// ClearPwd clears the value of the "pwd" field.
func (suo *SetupUpdateOne) ClearPwd() *SetupUpdateOne {
	suo.mutation.ClearPwd()
	return suo
}

// SetUuid1 sets the "uuid1" field.
func (suo *SetupUpdateOne) SetUuid1(s string) *SetupUpdateOne {
	suo.mutation.SetUuid1(s)
	return suo
}

// SetNillableUuid1 sets the "uuid1" field if the given value is not nil.
func (suo *SetupUpdateOne) SetNillableUuid1(s *string) *SetupUpdateOne {
	if s != nil {
		suo.SetUuid1(*s)
	}
	return suo
}

// SetUuid2 sets the "uuid2" field.
func (suo *SetupUpdateOne) SetUuid2(s string) *SetupUpdateOne {
	suo.mutation.SetUuid2(s)
	return suo
}

// SetNillableUuid2 sets the "uuid2" field if the given value is not nil.
func (suo *SetupUpdateOne) SetNillableUuid2(s *string) *SetupUpdateOne {
	if s != nil {
		suo.SetUuid2(*s)
	}
	return suo
}

// Mutation returns the SetupMutation object of the builder.
func (suo *SetupUpdateOne) Mutation() *SetupMutation {
	return suo.mutation
}

// Where appends a list predicates to the SetupUpdate builder.
func (suo *SetupUpdateOne) Where(ps ...predicate.Setup) *SetupUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SetupUpdateOne) Select(field string, fields ...string) *SetupUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Setup entity.
func (suo *SetupUpdateOne) Save(ctx context.Context) (*Setup, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SetupUpdateOne) SaveX(ctx context.Context) *Setup {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SetupUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SetupUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SetupUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdateTime(); !ok {
		v := setup.UpdateDefaultUpdateTime()
		suo.mutation.SetUpdateTime(v)
	}
	if _, ok := suo.mutation.LastTime(); !ok {
		v := setup.UpdateDefaultLastTime()
		suo.mutation.SetLastTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SetupUpdateOne) check() error {
	if v, ok := suo.mutation.IP(); ok {
		if err := setup.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Setup.ip": %w`, err)}
		}
	}
	if v, ok := suo.mutation.User(); ok {
		if err := setup.UserValidator(v); err != nil {
			return &ValidationError{Name: "user", err: fmt.Errorf(`ent: validator failed for field "Setup.user": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Pwd(); ok {
		if err := setup.PwdValidator(v); err != nil {
			return &ValidationError{Name: "pwd", err: fmt.Errorf(`ent: validator failed for field "Setup.pwd": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Uuid1(); ok {
		if err := setup.Uuid1Validator(v); err != nil {
			return &ValidationError{Name: "uuid1", err: fmt.Errorf(`ent: validator failed for field "Setup.uuid1": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Uuid2(); ok {
		if err := setup.Uuid2Validator(v); err != nil {
			return &ValidationError{Name: "uuid2", err: fmt.Errorf(`ent: validator failed for field "Setup.uuid2": %w`, err)}
		}
	}
	return nil
}

func (suo *SetupUpdateOne) sqlSave(ctx context.Context) (_node *Setup, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(setup.Table, setup.Columns, sqlgraph.NewFieldSpec(setup.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Setup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, setup.FieldID)
		for _, f := range fields {
			if !setup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != setup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdateTime(); ok {
		_spec.SetField(setup.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.IP(); ok {
		_spec.SetField(setup.FieldIP, field.TypeString, value)
	}
	if value, ok := suo.mutation.LastTime(); ok {
		_spec.SetField(setup.FieldLastTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.User(); ok {
		_spec.SetField(setup.FieldUser, field.TypeString, value)
	}
	if suo.mutation.UserCleared() {
		_spec.ClearField(setup.FieldUser, field.TypeString)
	}
	if value, ok := suo.mutation.Pwd(); ok {
		_spec.SetField(setup.FieldPwd, field.TypeString, value)
	}
	if suo.mutation.PwdCleared() {
		_spec.ClearField(setup.FieldPwd, field.TypeString)
	}
	if value, ok := suo.mutation.Uuid1(); ok {
		_spec.SetField(setup.FieldUuid1, field.TypeString, value)
	}
	if value, ok := suo.mutation.Uuid2(); ok {
		_spec.SetField(setup.FieldUuid2, field.TypeString, value)
	}
	_node = &Setup{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{setup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
