// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/doggy/orm/ent/predicate"
	"github.com/twiglab/doggy/orm/ent/upload"
)

// UploadUpdate is the builder for updating Upload entities.
type UploadUpdate struct {
	config
	hooks    []Hook
	mutation *UploadMutation
}

// Where appends a list predicates to the UploadUpdate builder.
func (uu *UploadUpdate) Where(ps ...predicate.Upload) *UploadUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUpdateTime sets the "update_time" field.
func (uu *UploadUpdate) SetUpdateTime(t time.Time) *UploadUpdate {
	uu.mutation.SetUpdateTime(t)
	return uu
}

// SetIP sets the "ip" field.
func (uu *UploadUpdate) SetIP(s string) *UploadUpdate {
	uu.mutation.SetIP(s)
	return uu
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (uu *UploadUpdate) SetNillableIP(s *string) *UploadUpdate {
	if s != nil {
		uu.SetIP(*s)
	}
	return uu
}

// SetUUID sets the "uuid" field.
func (uu *UploadUpdate) SetUUID(s string) *UploadUpdate {
	uu.mutation.SetUUID(s)
	return uu
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (uu *UploadUpdate) SetNillableUUID(s *string) *UploadUpdate {
	if s != nil {
		uu.SetUUID(*s)
	}
	return uu
}

// ClearUUID clears the value of the "uuid" field.
func (uu *UploadUpdate) ClearUUID() *UploadUpdate {
	uu.mutation.ClearUUID()
	return uu
}

// SetDeviceID sets the "device_id" field.
func (uu *UploadUpdate) SetDeviceID(s string) *UploadUpdate {
	uu.mutation.SetDeviceID(s)
	return uu
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (uu *UploadUpdate) SetNillableDeviceID(s *string) *UploadUpdate {
	if s != nil {
		uu.SetDeviceID(*s)
	}
	return uu
}

// ClearDeviceID clears the value of the "device_id" field.
func (uu *UploadUpdate) ClearDeviceID() *UploadUpdate {
	uu.mutation.ClearDeviceID()
	return uu
}

// SetLastTime sets the "last_time" field.
func (uu *UploadUpdate) SetLastTime(t time.Time) *UploadUpdate {
	uu.mutation.SetLastTime(t)
	return uu
}

// SetUser sets the "user" field.
func (uu *UploadUpdate) SetUser(s string) *UploadUpdate {
	uu.mutation.SetUser(s)
	return uu
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (uu *UploadUpdate) SetNillableUser(s *string) *UploadUpdate {
	if s != nil {
		uu.SetUser(*s)
	}
	return uu
}

// ClearUser clears the value of the "user" field.
func (uu *UploadUpdate) ClearUser() *UploadUpdate {
	uu.mutation.ClearUser()
	return uu
}

// SetPwd sets the "pwd" field.
func (uu *UploadUpdate) SetPwd(s string) *UploadUpdate {
	uu.mutation.SetPwd(s)
	return uu
}

// SetNillablePwd sets the "pwd" field if the given value is not nil.
func (uu *UploadUpdate) SetNillablePwd(s *string) *UploadUpdate {
	if s != nil {
		uu.SetPwd(*s)
	}
	return uu
}

// ClearPwd clears the value of the "pwd" field.
func (uu *UploadUpdate) ClearPwd() *UploadUpdate {
	uu.mutation.ClearPwd()
	return uu
}

// Mutation returns the UploadMutation object of the builder.
func (uu *UploadUpdate) Mutation() *UploadMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UploadUpdate) Save(ctx context.Context) (int, error) {
	uu.defaults()
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UploadUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UploadUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UploadUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uu *UploadUpdate) defaults() {
	if _, ok := uu.mutation.UpdateTime(); !ok {
		v := upload.UpdateDefaultUpdateTime()
		uu.mutation.SetUpdateTime(v)
	}
	if _, ok := uu.mutation.LastTime(); !ok {
		v := upload.UpdateDefaultLastTime()
		uu.mutation.SetLastTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UploadUpdate) check() error {
	if v, ok := uu.mutation.IP(); ok {
		if err := upload.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Upload.ip": %w`, err)}
		}
	}
	if v, ok := uu.mutation.UUID(); ok {
		if err := upload.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "Upload.uuid": %w`, err)}
		}
	}
	if v, ok := uu.mutation.DeviceID(); ok {
		if err := upload.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Upload.device_id": %w`, err)}
		}
	}
	if v, ok := uu.mutation.User(); ok {
		if err := upload.UserValidator(v); err != nil {
			return &ValidationError{Name: "user", err: fmt.Errorf(`ent: validator failed for field "Upload.user": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Pwd(); ok {
		if err := upload.PwdValidator(v); err != nil {
			return &ValidationError{Name: "pwd", err: fmt.Errorf(`ent: validator failed for field "Upload.pwd": %w`, err)}
		}
	}
	return nil
}

func (uu *UploadUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.UpdateTime(); ok {
		_spec.SetField(upload.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := uu.mutation.IP(); ok {
		_spec.SetField(upload.FieldIP, field.TypeString, value)
	}
	if value, ok := uu.mutation.UUID(); ok {
		_spec.SetField(upload.FieldUUID, field.TypeString, value)
	}
	if uu.mutation.UUIDCleared() {
		_spec.ClearField(upload.FieldUUID, field.TypeString)
	}
	if value, ok := uu.mutation.DeviceID(); ok {
		_spec.SetField(upload.FieldDeviceID, field.TypeString, value)
	}
	if uu.mutation.DeviceIDCleared() {
		_spec.ClearField(upload.FieldDeviceID, field.TypeString)
	}
	if value, ok := uu.mutation.LastTime(); ok {
		_spec.SetField(upload.FieldLastTime, field.TypeTime, value)
	}
	if value, ok := uu.mutation.User(); ok {
		_spec.SetField(upload.FieldUser, field.TypeString, value)
	}
	if uu.mutation.UserCleared() {
		_spec.ClearField(upload.FieldUser, field.TypeString)
	}
	if value, ok := uu.mutation.Pwd(); ok {
		_spec.SetField(upload.FieldPwd, field.TypeString, value)
	}
	if uu.mutation.PwdCleared() {
		_spec.ClearField(upload.FieldPwd, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UploadUpdateOne is the builder for updating a single Upload entity.
type UploadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UploadMutation
}

// SetUpdateTime sets the "update_time" field.
func (uuo *UploadUpdateOne) SetUpdateTime(t time.Time) *UploadUpdateOne {
	uuo.mutation.SetUpdateTime(t)
	return uuo
}

// SetIP sets the "ip" field.
func (uuo *UploadUpdateOne) SetIP(s string) *UploadUpdateOne {
	uuo.mutation.SetIP(s)
	return uuo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (uuo *UploadUpdateOne) SetNillableIP(s *string) *UploadUpdateOne {
	if s != nil {
		uuo.SetIP(*s)
	}
	return uuo
}

// SetUUID sets the "uuid" field.
func (uuo *UploadUpdateOne) SetUUID(s string) *UploadUpdateOne {
	uuo.mutation.SetUUID(s)
	return uuo
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (uuo *UploadUpdateOne) SetNillableUUID(s *string) *UploadUpdateOne {
	if s != nil {
		uuo.SetUUID(*s)
	}
	return uuo
}

// ClearUUID clears the value of the "uuid" field.
func (uuo *UploadUpdateOne) ClearUUID() *UploadUpdateOne {
	uuo.mutation.ClearUUID()
	return uuo
}

// SetDeviceID sets the "device_id" field.
func (uuo *UploadUpdateOne) SetDeviceID(s string) *UploadUpdateOne {
	uuo.mutation.SetDeviceID(s)
	return uuo
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (uuo *UploadUpdateOne) SetNillableDeviceID(s *string) *UploadUpdateOne {
	if s != nil {
		uuo.SetDeviceID(*s)
	}
	return uuo
}

// ClearDeviceID clears the value of the "device_id" field.
func (uuo *UploadUpdateOne) ClearDeviceID() *UploadUpdateOne {
	uuo.mutation.ClearDeviceID()
	return uuo
}

// SetLastTime sets the "last_time" field.
func (uuo *UploadUpdateOne) SetLastTime(t time.Time) *UploadUpdateOne {
	uuo.mutation.SetLastTime(t)
	return uuo
}

// SetUser sets the "user" field.
func (uuo *UploadUpdateOne) SetUser(s string) *UploadUpdateOne {
	uuo.mutation.SetUser(s)
	return uuo
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (uuo *UploadUpdateOne) SetNillableUser(s *string) *UploadUpdateOne {
	if s != nil {
		uuo.SetUser(*s)
	}
	return uuo
}

// ClearUser clears the value of the "user" field.
func (uuo *UploadUpdateOne) ClearUser() *UploadUpdateOne {
	uuo.mutation.ClearUser()
	return uuo
}

// SetPwd sets the "pwd" field.
func (uuo *UploadUpdateOne) SetPwd(s string) *UploadUpdateOne {
	uuo.mutation.SetPwd(s)
	return uuo
}

// SetNillablePwd sets the "pwd" field if the given value is not nil.
func (uuo *UploadUpdateOne) SetNillablePwd(s *string) *UploadUpdateOne {
	if s != nil {
		uuo.SetPwd(*s)
	}
	return uuo
}

// ClearPwd clears the value of the "pwd" field.
func (uuo *UploadUpdateOne) ClearPwd() *UploadUpdateOne {
	uuo.mutation.ClearPwd()
	return uuo
}

// Mutation returns the UploadMutation object of the builder.
func (uuo *UploadUpdateOne) Mutation() *UploadMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UploadUpdate builder.
func (uuo *UploadUpdateOne) Where(ps ...predicate.Upload) *UploadUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UploadUpdateOne) Select(field string, fields ...string) *UploadUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated Upload entity.
func (uuo *UploadUpdateOne) Save(ctx context.Context) (*Upload, error) {
	uuo.defaults()
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UploadUpdateOne) SaveX(ctx context.Context) *Upload {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UploadUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UploadUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uuo *UploadUpdateOne) defaults() {
	if _, ok := uuo.mutation.UpdateTime(); !ok {
		v := upload.UpdateDefaultUpdateTime()
		uuo.mutation.SetUpdateTime(v)
	}
	if _, ok := uuo.mutation.LastTime(); !ok {
		v := upload.UpdateDefaultLastTime()
		uuo.mutation.SetLastTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UploadUpdateOne) check() error {
	if v, ok := uuo.mutation.IP(); ok {
		if err := upload.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Upload.ip": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.UUID(); ok {
		if err := upload.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "Upload.uuid": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.DeviceID(); ok {
		if err := upload.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Upload.device_id": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.User(); ok {
		if err := upload.UserValidator(v); err != nil {
			return &ValidationError{Name: "user", err: fmt.Errorf(`ent: validator failed for field "Upload.user": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Pwd(); ok {
		if err := upload.PwdValidator(v); err != nil {
			return &ValidationError{Name: "pwd", err: fmt.Errorf(`ent: validator failed for field "Upload.pwd": %w`, err)}
		}
	}
	return nil
}

func (uuo *UploadUpdateOne) sqlSave(ctx context.Context) (_node *Upload, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Upload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upload.FieldID)
		for _, f := range fields {
			if !upload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.UpdateTime(); ok {
		_spec.SetField(upload.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.IP(); ok {
		_spec.SetField(upload.FieldIP, field.TypeString, value)
	}
	if value, ok := uuo.mutation.UUID(); ok {
		_spec.SetField(upload.FieldUUID, field.TypeString, value)
	}
	if uuo.mutation.UUIDCleared() {
		_spec.ClearField(upload.FieldUUID, field.TypeString)
	}
	if value, ok := uuo.mutation.DeviceID(); ok {
		_spec.SetField(upload.FieldDeviceID, field.TypeString, value)
	}
	if uuo.mutation.DeviceIDCleared() {
		_spec.ClearField(upload.FieldDeviceID, field.TypeString)
	}
	if value, ok := uuo.mutation.LastTime(); ok {
		_spec.SetField(upload.FieldLastTime, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.User(); ok {
		_spec.SetField(upload.FieldUser, field.TypeString, value)
	}
	if uuo.mutation.UserCleared() {
		_spec.ClearField(upload.FieldUser, field.TypeString)
	}
	if value, ok := uuo.mutation.Pwd(); ok {
		_spec.SetField(upload.FieldPwd, field.TypeString, value)
	}
	if uuo.mutation.PwdCleared() {
		_spec.ClearField(upload.FieldPwd, field.TypeString)
	}
	_node = &Upload{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
