// Code generated by ent, DO NOT EDIT.

package upload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/doggy/orm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldUpdateTime, v))
}

// Sn applies equality check predicate on the "sn" field. It's identical to SnEQ.
func Sn(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldSn, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldIP, v))
}

// LastTime applies equality check predicate on the "last_time" field. It's identical to LastTimeEQ.
func LastTime(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldLastTime, v))
}

// ID1 applies equality check predicate on the "id_1" field. It's identical to ID1EQ.
func ID1(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldID1, v))
}

// Code1 applies equality check predicate on the "code_1" field. It's identical to Code1EQ.
func Code1(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCode1, v))
}

// User applies equality check predicate on the "user" field. It's identical to UserEQ.
func User(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldUser, v))
}

// Pwd applies equality check predicate on the "pwd" field. It's identical to PwdEQ.
func Pwd(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldPwd, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldUpdateTime, v))
}

// SnEQ applies the EQ predicate on the "sn" field.
func SnEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldSn, v))
}

// SnNEQ applies the NEQ predicate on the "sn" field.
func SnNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldSn, v))
}

// SnIn applies the In predicate on the "sn" field.
func SnIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldSn, vs...))
}

// SnNotIn applies the NotIn predicate on the "sn" field.
func SnNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldSn, vs...))
}

// SnGT applies the GT predicate on the "sn" field.
func SnGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldSn, v))
}

// SnGTE applies the GTE predicate on the "sn" field.
func SnGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldSn, v))
}

// SnLT applies the LT predicate on the "sn" field.
func SnLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldSn, v))
}

// SnLTE applies the LTE predicate on the "sn" field.
func SnLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldSn, v))
}

// SnContains applies the Contains predicate on the "sn" field.
func SnContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldSn, v))
}

// SnHasPrefix applies the HasPrefix predicate on the "sn" field.
func SnHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldSn, v))
}

// SnHasSuffix applies the HasSuffix predicate on the "sn" field.
func SnHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldSn, v))
}

// SnEqualFold applies the EqualFold predicate on the "sn" field.
func SnEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldSn, v))
}

// SnContainsFold applies the ContainsFold predicate on the "sn" field.
func SnContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldSn, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldIP, v))
}

// LastTimeEQ applies the EQ predicate on the "last_time" field.
func LastTimeEQ(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldLastTime, v))
}

// LastTimeNEQ applies the NEQ predicate on the "last_time" field.
func LastTimeNEQ(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldLastTime, v))
}

// LastTimeIn applies the In predicate on the "last_time" field.
func LastTimeIn(vs ...time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldLastTime, vs...))
}

// LastTimeNotIn applies the NotIn predicate on the "last_time" field.
func LastTimeNotIn(vs ...time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldLastTime, vs...))
}

// LastTimeGT applies the GT predicate on the "last_time" field.
func LastTimeGT(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldLastTime, v))
}

// LastTimeGTE applies the GTE predicate on the "last_time" field.
func LastTimeGTE(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldLastTime, v))
}

// LastTimeLT applies the LT predicate on the "last_time" field.
func LastTimeLT(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldLastTime, v))
}

// LastTimeLTE applies the LTE predicate on the "last_time" field.
func LastTimeLTE(v time.Time) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldLastTime, v))
}

// ID1EQ applies the EQ predicate on the "id_1" field.
func ID1EQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldID1, v))
}

// ID1NEQ applies the NEQ predicate on the "id_1" field.
func ID1NEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldID1, v))
}

// ID1In applies the In predicate on the "id_1" field.
func ID1In(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldID1, vs...))
}

// ID1NotIn applies the NotIn predicate on the "id_1" field.
func ID1NotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldID1, vs...))
}

// ID1GT applies the GT predicate on the "id_1" field.
func ID1GT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldID1, v))
}

// ID1GTE applies the GTE predicate on the "id_1" field.
func ID1GTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldID1, v))
}

// ID1LT applies the LT predicate on the "id_1" field.
func ID1LT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldID1, v))
}

// ID1LTE applies the LTE predicate on the "id_1" field.
func ID1LTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldID1, v))
}

// ID1Contains applies the Contains predicate on the "id_1" field.
func ID1Contains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldID1, v))
}

// ID1HasPrefix applies the HasPrefix predicate on the "id_1" field.
func ID1HasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldID1, v))
}

// ID1HasSuffix applies the HasSuffix predicate on the "id_1" field.
func ID1HasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldID1, v))
}

// ID1IsNil applies the IsNil predicate on the "id_1" field.
func ID1IsNil() predicate.Upload {
	return predicate.Upload(sql.FieldIsNull(FieldID1))
}

// ID1NotNil applies the NotNil predicate on the "id_1" field.
func ID1NotNil() predicate.Upload {
	return predicate.Upload(sql.FieldNotNull(FieldID1))
}

// ID1EqualFold applies the EqualFold predicate on the "id_1" field.
func ID1EqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldID1, v))
}

// ID1ContainsFold applies the ContainsFold predicate on the "id_1" field.
func ID1ContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldID1, v))
}

// Code1EQ applies the EQ predicate on the "code_1" field.
func Code1EQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldCode1, v))
}

// Code1NEQ applies the NEQ predicate on the "code_1" field.
func Code1NEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldCode1, v))
}

// Code1In applies the In predicate on the "code_1" field.
func Code1In(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldCode1, vs...))
}

// Code1NotIn applies the NotIn predicate on the "code_1" field.
func Code1NotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldCode1, vs...))
}

// Code1GT applies the GT predicate on the "code_1" field.
func Code1GT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldCode1, v))
}

// Code1GTE applies the GTE predicate on the "code_1" field.
func Code1GTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldCode1, v))
}

// Code1LT applies the LT predicate on the "code_1" field.
func Code1LT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldCode1, v))
}

// Code1LTE applies the LTE predicate on the "code_1" field.
func Code1LTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldCode1, v))
}

// Code1Contains applies the Contains predicate on the "code_1" field.
func Code1Contains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldCode1, v))
}

// Code1HasPrefix applies the HasPrefix predicate on the "code_1" field.
func Code1HasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldCode1, v))
}

// Code1HasSuffix applies the HasSuffix predicate on the "code_1" field.
func Code1HasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldCode1, v))
}

// Code1IsNil applies the IsNil predicate on the "code_1" field.
func Code1IsNil() predicate.Upload {
	return predicate.Upload(sql.FieldIsNull(FieldCode1))
}

// Code1NotNil applies the NotNil predicate on the "code_1" field.
func Code1NotNil() predicate.Upload {
	return predicate.Upload(sql.FieldNotNull(FieldCode1))
}

// Code1EqualFold applies the EqualFold predicate on the "code_1" field.
func Code1EqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldCode1, v))
}

// Code1ContainsFold applies the ContainsFold predicate on the "code_1" field.
func Code1ContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldCode1, v))
}

// UserEQ applies the EQ predicate on the "user" field.
func UserEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldUser, v))
}

// UserNEQ applies the NEQ predicate on the "user" field.
func UserNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldUser, v))
}

// UserIn applies the In predicate on the "user" field.
func UserIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldUser, vs...))
}

// UserNotIn applies the NotIn predicate on the "user" field.
func UserNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldUser, vs...))
}

// UserGT applies the GT predicate on the "user" field.
func UserGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldUser, v))
}

// UserGTE applies the GTE predicate on the "user" field.
func UserGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldUser, v))
}

// UserLT applies the LT predicate on the "user" field.
func UserLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldUser, v))
}

// UserLTE applies the LTE predicate on the "user" field.
func UserLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldUser, v))
}

// UserContains applies the Contains predicate on the "user" field.
func UserContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldUser, v))
}

// UserHasPrefix applies the HasPrefix predicate on the "user" field.
func UserHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldUser, v))
}

// UserHasSuffix applies the HasSuffix predicate on the "user" field.
func UserHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldUser, v))
}

// UserIsNil applies the IsNil predicate on the "user" field.
func UserIsNil() predicate.Upload {
	return predicate.Upload(sql.FieldIsNull(FieldUser))
}

// UserNotNil applies the NotNil predicate on the "user" field.
func UserNotNil() predicate.Upload {
	return predicate.Upload(sql.FieldNotNull(FieldUser))
}

// UserEqualFold applies the EqualFold predicate on the "user" field.
func UserEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldUser, v))
}

// UserContainsFold applies the ContainsFold predicate on the "user" field.
func UserContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldUser, v))
}

// PwdEQ applies the EQ predicate on the "pwd" field.
func PwdEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEQ(FieldPwd, v))
}

// PwdNEQ applies the NEQ predicate on the "pwd" field.
func PwdNEQ(v string) predicate.Upload {
	return predicate.Upload(sql.FieldNEQ(FieldPwd, v))
}

// PwdIn applies the In predicate on the "pwd" field.
func PwdIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldIn(FieldPwd, vs...))
}

// PwdNotIn applies the NotIn predicate on the "pwd" field.
func PwdNotIn(vs ...string) predicate.Upload {
	return predicate.Upload(sql.FieldNotIn(FieldPwd, vs...))
}

// PwdGT applies the GT predicate on the "pwd" field.
func PwdGT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGT(FieldPwd, v))
}

// PwdGTE applies the GTE predicate on the "pwd" field.
func PwdGTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldGTE(FieldPwd, v))
}

// PwdLT applies the LT predicate on the "pwd" field.
func PwdLT(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLT(FieldPwd, v))
}

// PwdLTE applies the LTE predicate on the "pwd" field.
func PwdLTE(v string) predicate.Upload {
	return predicate.Upload(sql.FieldLTE(FieldPwd, v))
}

// PwdContains applies the Contains predicate on the "pwd" field.
func PwdContains(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContains(FieldPwd, v))
}

// PwdHasPrefix applies the HasPrefix predicate on the "pwd" field.
func PwdHasPrefix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasPrefix(FieldPwd, v))
}

// PwdHasSuffix applies the HasSuffix predicate on the "pwd" field.
func PwdHasSuffix(v string) predicate.Upload {
	return predicate.Upload(sql.FieldHasSuffix(FieldPwd, v))
}

// PwdIsNil applies the IsNil predicate on the "pwd" field.
func PwdIsNil() predicate.Upload {
	return predicate.Upload(sql.FieldIsNull(FieldPwd))
}

// PwdNotNil applies the NotNil predicate on the "pwd" field.
func PwdNotNil() predicate.Upload {
	return predicate.Upload(sql.FieldNotNull(FieldPwd))
}

// PwdEqualFold applies the EqualFold predicate on the "pwd" field.
func PwdEqualFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldEqualFold(FieldPwd, v))
}

// PwdContainsFold applies the ContainsFold predicate on the "pwd" field.
func PwdContainsFold(v string) predicate.Upload {
	return predicate.Upload(sql.FieldContainsFold(FieldPwd, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Upload) predicate.Upload {
	return predicate.Upload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Upload) predicate.Upload {
	return predicate.Upload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Upload) predicate.Upload {
	return predicate.Upload(sql.NotPredicates(p))
}
