// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Point is the predicate function for point builders.
type Point func(*sql.Selector)

// Upload is the predicate function for upload builders.
type Upload func(*sql.Selector)

// Using is the predicate function for using builders.
type Using func(*sql.Selector)
