// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AutoRegColumns holds the columns for the "auto_reg" table.
	AutoRegColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "sn", Type: field.TypeString, Unique: true, Size: 36, SchemaType: map[string]string{"mysql": "char(36)", "postgres": "char(36)", "sqlite3": "char(36)"}},
		{Name: "ip", Type: field.TypeString, Size: 64, SchemaType: map[string]string{"mysql": "varchar(32)", "postgres": "varchar(32)", "sqlite3": "varchar(32)"}},
	}
	// AutoRegTable holds the schema information for the "auto_reg" table.
	AutoRegTable = &schema.Table{
		Name:       "auto_reg",
		Columns:    AutoRegColumns,
		PrimaryKey: []*schema.Column{AutoRegColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AutoRegTable,
	}
)

func init() {
	AutoRegTable.Annotation = &entsql.Annotation{
		Table: "auto_reg",
	}
}
